export const constants = {
    HUB_URL:"",
    STORAGE_KEY: "STORAGE_KEY",
    ACCESS_TOKEN_KEY: "ACCESS_TOKEN_KEY",
    LOGIN_CREDENTIALS: "LOGIN_CREDENTIALS",
    CURRENT_PROFILE_KEY: "CURRENT_PROFILE_KEY",
    CURRENT_TEAM_KEY:"CURRENT_TEAM_KEY"
};